# Generated by Django 6.0.1 on 2026-02-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='is_book',
            new_name='is_booked',
        ),
        migrations.AddField(
            model_name='bus',
            name='no_of_seats',
            field=models.PositiveBigIntegerField(default=20),
            preserve_default=False,
        ),
    ]
